sudo: required
services:
  - docker

before_install:
  - docker build -t subramanian05docker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true subramanian05docker/docker-react npm run test
